### ISSUE TITLE
LOG: 2019-09-02 HDAWG disconnection-Aprilia Fridge

### ISSUE THREAD

**Issue by hasali92** [DiCarloLab-Delft/PycQED_py3#582] opened 2019-09-02 12:23 UTC
## Error report and solution :

A problem: an error during an overnight run >> it complains that ZI-HDAWG  is  not found i.e. disconnected.

Indeed, I did not find  HDAWG on LABone  website, http://127.0.0.1:8006/

Solutions I tried:

Step 1: i did power cycle the ZI_HDWG (reset: off and on)

Step 2: Reload the setting of HAWG >> by running this code below:

### ###############################################################

# HDAWG

ts=None

reload(ZI_HDAWG8.zs)

reload(ZI_HDAWG8)

AWG8_8066.close()

del station.components['AWG8_8066']

AWG8_8066 = ZI_HDAWG8.ZI_HDAWG8('AWG8_8066', device='dev8066')

station.add_component(AWG8_8066, update_snapshot=False)

AWG8_8066.cfg_codeword_protocol('microwave')

##################################################################

Step 3: Calibrate the DOI >> open this link 

 http://localhost:8888/tree/iPython-Notebooks/Electronics_Design

and then open AWG8_V4_DIO_Calibration. Change the instrument code and choose the control mode. Then, run all the cells. It chooses the right setting i.e. delay time for DIO … etc. 
>> The calibration was done successfully.

Result:

HDAWG is back and I can communicate with it.

However, the problem came back a day after and I did power cycle the HDAWG and did the steps above. It worked perfectly for 2 hours, but the problem came back again.

Current situation:

I couldn't run a successful overnight run.

**Comment by AdriaanRol** [comment] 2019-09-02 12:41
@hasali92 . This is a duplicate of https://github.com/DiCarloLab-Delft/QuSurf-IssueTracker/issues/145 . 
Whenever reporting issues with ZI hardware it is useful to look if an issue already exists in the QuSurf issue tracker.

**Closed by AdriaanRol** 2019-09-02 12:41 UTC
