### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#629] opened 2020-04-29 14:17 UTC
Tests are failing.

**Comment by elrama-** [comment] 2020-06-18 15:22
Last working commit 
https://github.com/DiCarloLab-Delft/PycQED_py3/commit/02aa60ca7c41cbf80329a7a8ec2060a48fe10a31

**Comment by caenrigen** [comment] 2020-07-22 19:05
@MiguelSMoreira need some help

I fixed a bunch of tests, need some help on a particular question that is making many tests in qubits and device objects fail:
In 1932bbc79be7bf5b7fd9857f59d658a33067278e we added a `self.UHFQC.sync()` but the `MockDAQServer` in `ZI_base_instrument.py` does not have a `.sync()` method. `UHFQC.sync()` under the hood calls the `sync()` of a DAQ object.
I don't feel qualified for this.
In order to make the test pass do we need just a `sync()` method in the `MockDAQServer` that does nothing?

I would appreciate if you could fix implement a solution for this

**Comment by nielshaandbaek** [comment] 2020-07-23 05:10
https://github.com/DiCarloLab-Delft/PycQED_py3/pull/634

**Comment by caenrigen** [comment] 2020-07-23 13:29
@MiguelSMoreira next very important one, CC related, makes `test_CC` and `test_device_objects` fail. It seems to be to some change in communication protocol and maybe the problem is only updating the tests. Hope you can tell who can have a look at this
```python
pycqed/instrument_drivers/physical_instruments/QuTech/CC.py:309: in set_func
    return fun(par1, val)
pycqed/instrument_drivers/physical_instruments/QuTech/CC.py:176: in _set_dio_delay
    self.stop()
pycqed/instrument_drivers/physical_instruments/QuTech/CCCore.py:144: in stop
    self.get_operation_complete()
pycqed/instrument_drivers/library/SCPIBase.py:66: in get_operation_complete
    return self._ask('*OPC?')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <CC: cc>, cmd_str = '*OPC?'

    def _ask(self, cmd_str: str) -> str:
        self._transport.write(cmd_str)
>       return self._transport.readline().rstrip()  # remove trailing white space, CR, LF
E       AttributeError: ("'NoneType' object has no attribute 'rstrip'", 'setting cc_dio0_out_delay to 0')

pycqed/instrument_drivers/library/SCPIBase.py:176: AttributeError
```

**Comment by caenrigen** [comment] 2020-07-23 13:50
@MiguelSMoreira now there is a dependency installation issue and can't have the CI tests to run 😑

**Comment by caenrigen** [comment] 2020-07-29 16:22
> @MiguelSMoreira next very important one, CC related, makes `test_CC` and `test_device_objects` fail. It seems to be to some change in communication protocol and maybe the problem is only updating the tests. Hope you can tell who can have a look at this
> 
> ```python
> pycqed/instrument_drivers/physical_instruments/QuTech/CC.py:309: in set_func
>     return fun(par1, val)
> pycqed/instrument_drivers/physical_instruments/QuTech/CC.py:176: in _set_dio_delay
>     self.stop()
> pycqed/instrument_drivers/physical_instruments/QuTech/CCCore.py:144: in stop
>     self.get_operation_complete()
> pycqed/instrument_drivers/library/SCPIBase.py:66: in get_operation_complete
>     return self._ask('*OPC?')
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <CC: cc>, cmd_str = '*OPC?'
> 
>     def _ask(self, cmd_str: str) -> str:
>         self._transport.write(cmd_str)
> >       return self._transport.readline().rstrip()  # remove trailing white space, CR, LF
> E       AttributeError: ("'NoneType' object has no attribute 'rstrip'", 'setting cc_dio0_out_delay to 0')
> 
> pycqed/instrument_drivers/library/SCPIBase.py:176: AttributeError
> ```

@wvlothuizen could you help with this failing test? Miguel and me do not know what is this due to, we are trying to gradually fix pycqed tests

**Comment by wvlothuizen** [comment] 2020-07-30 14:25
my bad, will try to fix this week

**Comment by wvlothuizen** [comment] 2020-07-31 07:26
these two are solved in branch 'develop' now:

![image](https://user-images.githubusercontent.com/10208538/89010963-df25fb80-d30f-11ea-98ca-5f99103fe765.png)

**Comment by caenrigen** [comment] 2020-08-06 12:49
@wvlothuizen as discussed a bit ago there is this error in the tests related to the `QWG`/`ip`/communication protocol
here a handy line to run the specific test:
```
pytest pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py -v -k test_uploading_standard_pulses_QWG_lutman
```

**Comment by caenrigen** [comment] 2020-08-06 13:54
> @wvlothuizen as discussed a bit ago there is this error in the tests related to the `QWG`/`ip`/communication protocol
> here a handy line to run the specific test:
> 
> ```
> pytest pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py -v -k test_uploading_standard_pulses_QWG_lutman
> ```

I believe after fixing this error we should have the test on `develop` back on track 😊

**Comment by wvlothuizen** [comment] 2020-08-07 10:05
the test succeed again, let's also merge to master
![image](https://user-images.githubusercontent.com/10208538/89634845-4f9bc200-d8a6-11ea-9ff8-a3bcd24d33f4.png)

**Comment by wvlothuizen** [comment] 2020-12-09 19:43
test were fixed, so closing, although they now fail again

**Closed by wvlothuizen** 2020-12-09 19:43 UTC
