### ISSUE TITLE
Console becomes irresponsive when compiling OpenQL program

### ISSUE THREAD

**Issue by wvlothuizen** [DiCarloLab-Delft/PycQED_py3#696] opened 2022-04-07 07:06 UTC
Issue by Miguel:

... a problem we have observed in the Pagani setup.

Having updated PycQED to the most recent commit (after quite some work merging with the local branch in this setup), we noticed that when compiling any program in OpenQL the console becomes irresponsible and we observe a sudden spike in the utilization of RAM memory. Whether this is due to an infinite loop or a memory leak is undetermined at this point. The result of the merge is pointed to by the link below and the latest commit of the develop branch (where we stand) by the link below that:
https://github.com/DiCarloLab-Delft/PycQED_py3/commit/f41d7785ea96c68e2b400ee791f8d93bd8b571cf
https://github.com/DiCarloLab-Delft/PycQED_py3/commit/7857e714a93c39c5fcc504249d1135f582bef9ed

**Comment by wvlothuizen** [comment] 2022-04-07 07:09
There seems to be hardly any difference between the two commits mentioned, but commit b2e571fb4c5d436c69a98c9b710e3bb3018ece14 (Local changes in the Pagani setup) does introduce many changes.

A PR for this would have been nice, but we can see the differences in https://github.com/DiCarloLab-Delft/PycQED_py3/compare/c07ae94ab896b9bc76a43e69d07fe855528f9ae3...develop

**Comment by wvlothuizen** [comment] 2022-04-07 07:55
@MiguelSMoreira 

Sort of reviewed the differences as shown above:
- HAL_Device.py has undergone extensive cleanup, but has 10 errors (according to PyCharm): nothing that could break compilation totally
- HAL_Transmon.py has 7 errors, mostly in calibrate_depletion_pulse() (which seems to have been copy/pasted over the existing version) and calibrate_optimal_weights(). Again, nothing explaining the problem at hand
- clifford_rb_oql.py is WIP

So, I cannot imagine PycQED being the culprit. Things to try:
- use latest OpenQL version: `pip install qutechopenql --verbose --verbose --verbose --no-index -f https://github.com/DiCarloLab-Delft/OpenQL/releases`
- does the problem occur on >1 computers? If not, try another
- have a closer look with Task Manager

**Comment by MiguelSMoreira** [comment] 2022-04-12 15:10
cc: @wvlothuizen 

Upon further experimentation, I can confirm that this problem is only observed when compiling programs with OpenQL version 0.10.4 in the latest develop branch of PycQED_py3. When rolling back to OpenQL version 0.10.1 and the older branch of PycQED_py3, pagani_detached (before merge of remote/develop with local branch in Pagani), compilation can be carried out correctly across all experiments.

Furthermore, I wanted to detail the conditions under which the console becomes irresponsive. Various kernels and programs can be created and added without problem, it is only when calling p.compile() that we observe a sudden and sustained increase of system-memory use, leading to the eventual crash of the computer. The call p.compile() never returns.

**Comment by wvlothuizen** [comment] 2022-04-26 10:28
@MiguelSMoreira 

just checked PycQED branch 'develop' (commit d6b2348fa6046f9ca45b5f8f3391903870f93ac2) with OpenQL 0.10.4 on the development setup, and it passes all tests in `pytest -v .\pycqed\tests\openql\`

So I'm afraid the problem doesn't reproduce there ...

**Comment by MiguelSMoreira** [comment] 2022-04-26 12:02
@wvlothuizen 

As I understood from in-person discussions, the problem has been traced to the configuration file of OpenQL, particularly to a set of arguments/decompositions that led to the aforementioned behavior. At the time, I had asked @MiniSean to update this issue based on the solution he had found to this problem. Are there any updates on this @jorgemfm27 or @MiniSean ?

**Comment by MiniSean** [comment] 2022-04-26 13:46
@MiguelSMoreira, @wvlothuizen 

The problem we ran into was on a different setup from 'pagani' (namely the 'aprilia' setup) (at commit c07ae94a).
The syndrome looks very similar as to this issue: 
- Terminal becomes irresponsive (after calling `HAL_Transmon.measure_heterodyne_spectroscopy()` method).
- A slow buildup of memory usage (until system becomes unresponsive).

Our problem traced back to the start of a `OqlProgram.compile()` call, inside `single_qubit_oql.CW_RO_sequency()` method.

**Comment by MiguelSMoreira** [comment] 2022-04-26 13:50
@MiniSean 

Do I understand correctly that, after some experimentation with the OpenQL configuration file, you were able to modify some of its keys (or was it some of the available decomposition rules) in such a way as to prevent this problem? Could you then indicate exactly how you modified the configuration file to be able to run things smoothly? This would greatly help in establishing the reason behind the problem, leading to the implementation of a solution directly in OpenQL (or, at the very least, a more subtle way to handle this error in software).

**Comment by MiniSean** [comment] 2022-04-26 14:08
@MiguelSMoreira 

I am hesitant to say this is the silver bullet. But yes, in our case we seemed to have temporarily circumvented the issue by excluding a set of gate-decomposition key-value pairs from the config file: `pycqed\measurement\openql_experiments\config_cc_s17_direct_iq.json.in`. 
Keys that have been temporarily excluded are (where '#' is an arbitrary index):
- flux-dance-# q0
- flux-dance-refocus-# q0
- repetition-code-# q0

The reason we targeted this configuration file was because it was overwritten by the initial merge from remote.

**Comment by MiguelSMoreira** [comment] 2022-04-26 14:10
cc: @wvlothuizen 

Thank you @MiniSean! We understand this is all very preliminary information, I mainly requested it to help motivate further debugging, not necessarily to be taken as final. Thank you for your help with this!

**Comment by wvlothuizen** [comment] 2022-04-26 15:06
There's at least as issue with the naming: from OpenQL 0.9.0, instruction names can no longer contain "-", because that gave conflicts for cQASM which would interpret it as a minus-sign (identifiers with a "-" are a Bad Idea anyway).

I remember having edited the .json.in files to replace the  "-" with an "_", but that was probably undone in the merge.

I don't remember what actually happened when a "-" was present, but will take a look.

**Comment by MiniSean** [comment] 2022-04-26 16:00
@wvlothuizen
There is file with the same name (location: `pycqed\measurement\openql_experiments\config\config_cc_s17_direct_iq.json.in`).
Which has most, if not all identifiers using a "_" instead of "-". Is there a difference between the two files and which one should ideally be used?

**Comment by wvlothuizen** [comment] 2022-04-26 17:15
There are 2 scripts for configuration: the current/old `generate_CC_cfg.py` and the new `generate_CC_cfg_modular.py`. The file you quoted is used with the new script (as are the other files in the `config` subdirectory).

The idea behind the new script is to make the configuration modular, and reuse common parts (like the instructions in `common_instructions.json.in` or common gate decompositions in `common_gate_decomposition.json.in`) to simplify maintenance.

As such the new script is preferred, but it would work best if everyone switches at the same time. And although I tried to maintain compatibility, some work will probably be needed to port the latest additions of the old configuration file to the new files.

**Comment by wvlothuizen** [comment] 2022-04-26 18:22
Wrt to the dashes, I just checked, and using them in a gate name correctly riases an error:
`Usage error: in gate description for 'rx90-alpha': instruction name is not a valid identifier`

**Comment by wvlothuizen** [comment] 2022-05-02 11:30
I'm trying to track down the offending configuration file, but the following two do not contain the keys mentioned above (with dashes that is, e.g. `flux-dance-*`):
- https://github.com/DiCarloLab-Delft/PycQED_py3/blob/develop/pycqed/measurement/openql_experiments/config_cc_s17_direct_iq.json.in
- https://github.com/DiCarloLab-Delft/PycQED_py3/blob/pagani_detached/pycqed/measurement/openql_experiments/config_cc_s17_direct_iq.json.in

Where is the offending file located?

**Comment by MiniSean** [comment] 2022-05-12 11:10
The following configuration file:
- https://github.com/DiCarloLab-Delft/PycQED_py3/blob/develop/pycqed/measurement/openql_experiments/config_cc_s17_direct_iq.json.in

was indeed the one containing the mentioned (offending) keys.
For our next cooldown (Monday 16-May) I am planning to try and recreate this issue by moving to a clean `develop` commit `d6b2348f`. Update will follow then.

**Comment by wvlothuizen** [comment] 2022-05-23 12:50
Any news on this? I'm looking for a file that **does** give the problem, and one that **doesn't** (or exact instructions on how to turn one into the other)

**Comment by wvlothuizen** [comment] 2022-06-29 09:00
Ping!

**Comment by MiniSean** [comment] 2022-07-04 08:06
Able to reproduce the (or a similar) memory issue while working on the #692 issue. (Likely inherited the bug at the point of divergence from the develop branch. Not python 3.7 related)
No error response, just a slow accumulation of memory by the terminal until the operating system freezes.
Measurements using only the measurement controller (MC) and vector network analyzer (VNA) are executed without a problem.

Investigating further with @hasali92

**Comment by MiniSean** [comment] 2023-04-17 14:30
This was fixed with python 3.9 update for develop branch

**Closed as completed** 2023-04-17 14:29 UTC
